version: '3.8'

networks:
  transcendence:
    name: transcendence
    driver: bridge

# Database - PostgreSQL
services:
  postgres-db:
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--data-checksums"
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    networks:
      - transcendence
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Frontend - Django
  frontend:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: frontend
    networks:
      - transcendence
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    volumes:
      - ./ui:/app

  # Authentication service - Django
  user_management_service:
    container_name: user_management_service
    build:
      args:
        DJANGO_ROOT_PASSWORD: ${DJANGO_ROOT_PASSWORD}
      context: ./user_management_service/
      dockerfile: Dockerfile
    image: user_management_service
    networks:
      - transcendence
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
      - frontend
    volumes:
      - ./user_management_service:/app
    stop_grace_period: 2s

  # Nginx - Proxy Reverse
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    networks:
      - transcendence
    ports:
      - 80:80
    depends_on:
      - frontend
      - user_management_service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  # Two_Factor_authentication - Django
  two_factor_authentication:
    container_name: two_factor_authentication
    build:
      args:
        DJANGO_ROOT_PASSWORD: ${DJANGO_ROOT_PASSWORD}
      context: ./Two_Factor_authentication/
      dockerfile: Dockerfile
    image: two_factor_authentication
    networks:
      - transcendence
    ports:
      - 7575:7575
    env_file:
      - ./.env
    depends_on:
      - postgres-db
      - user_management_service
    volumes:
      - ./Two_Factor_authentication:/app
    stop_grace_period: 2s

    
volumes:
  postgres_data:
