version: '3.8'

networks:
  transcendence:
    name: transcendence
    driver: bridge

# Database - PostgreSQL
services:
  postgres-db:
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--data-checksums"
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    networks:
      - transcendence
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    networks:
      - transcendence
    ports:
      - 8081:8000  # Changed to avoid conflict with nginx
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app

  # Authentication service - Django
  user_management_service:
    container_name: user_management_service
    build:
      args:
        DJANGO_ROOT_PASSWORD: ${DJANGO_ROOT_PASSWORD}
      context: ./user_management_service/
      dockerfile: Dockerfile
    image: user_management_service
    networks:
      - transcendence
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    volumes:
      - ./user_management_service:/app
    stop_grace_period: 2s

  # Nginx - Proxy Reverse
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    networks:
      - transcendence
    ports:
      - 8080:80  # Keep this or change if needed
    depends_on:
      - frontend
      - user_management_service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
