version: '3.8'

networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  # Database - PostgreSQL
  postgres-db:
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--data-checksums"
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    networks:
      - transcendence
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend - Django
  django-backend:
    container_name: backend
    build:
      args:
        DJANGO_ROOT_PASSWORD: ${DJANGO_ROOT_PASSWORD}
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    networks:
      - transcendence
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    volumes:
      - ./backend:/app

  # Authentication service - Django
  auth_service:
    container_name: auth_service
    build:
      context: ./auth_service/
      dockerfile: Dockerfile
    image: auth_service
    networks:
      - transcendence
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
      - django-backend
    volumes:
      - ./auth_service:/app
    stop_grace_period: 2s

volumes:
  postgres_data:
