# Generated by Django 5.1.3 on 2024-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two_factor_autent', '0002_userloginattempt_last_successful_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginattempt',
            name='last_successful_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
