# Generated by Django 5.1.3 on 2025-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='opponent_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
