# Generated by Django 5.1.3 on 2025-01-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two_factor_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='userloginattempt',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
