# Generated by Django 5.1.3 on 2025-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two_factor_authentication', '0002_remove_userloginattempt_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginattempt',
            name='username',
        ),
        migrations.AddField(
            model_name='userloginattempt',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
